### ISSUE TITLE
Unable to train.

### ISSUE THREAD

**Issue by socekin** [fofr/replicate-llm-training#1]
Following the tutorial, an error occurred when starting the training.

`➜  replicate-llm-training git:(main) ✗ node train.js
/Users/username/replicate-llm-training/node_modules/replicate/index.js:154
      throw new Error(`API request failed: ${response.statusText}`);
            ^

Error: API request failed: Not Found
    at Replicate.request (/Users/username/replicate-llm-training/node_modules/replicate/index.js:154:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///Users/username/replicate-llm-training/train.js:26:20)`

**Comment by fofr** [comment]
@socekin Does your user have access to the fine-tune API? It's currently in beta and not every Replicate user has access to it.

I think that is why the API is returning Not found.

You can request access via team@replicate.com or on the Replicate Discord
